# Generated by Django 6.0 on 2026-01-04 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0003_alter_booking_dropoff_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_type', models.CharField(choices=[('RENTAL_FEE', 'Rental Fee'), ('SECURITY_DEPOSIT', 'Security Deposit'), ('LATE_FEE', 'Late Fee'), ('DAMAGE_CHARGE', 'Damage Charge')], default='RENTAL_FEE', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='PENDING', max_length=20)),
                ('provider', models.CharField(max_length=50)),
                ('provider_transaction_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('gateway_response_raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='rentals.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
