# Generated by Django 6.0 on 2026-01-01 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('PATONG', 'Patong'), ('KATA', 'Kata'), ('KARON', 'Karon'), ('PHUKET_TOWN', 'Phuket Town'), ('KAMALA', 'Kamala'), ('BANG_TAO', 'Bang Tao'), ('RAWAI', 'Rawai'), ('CHALONG', 'Chalong')], default='PATONG', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_note', models.TextField(blank=True, null=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('submitted_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
