# Generated by Django 6.0 on 2026-01-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agencymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
