# Generated by Django 6.0 on 2026-01-03 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_remove_location_agency_branch'),
        ('rentals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dropoff_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_bookings', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_bookings', to='branches.branch'),
        ),
    ]
