# Generated by Django 6.0 on 2026-01-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('is_pickup_point', models.BooleanField(default=False)),
                ('is_dropoff_point', models.BooleanField(default=False)),
            ],
        ),
    ]
