# Generated by Django 6.0 on 2026-01-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_remove_location_agency_branch'),
        ('rentals', '0003_alter_booking_dropoff_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
