#branches/serializers.py
from rest_framework import serializers
from .models import Branch

# lightweight serializer for branches: pickup dropdowns
class BranchListSerializer(serializers.ModelSerializer):
    class Meta:
        model = Branch
        fields = ['id',
                'name',
                'city',
                'slug',
                ]

# heavy serializer for branches: contacting and location pages
class BranchDetailSerializer(serializers.ModelSerializer):
    agency_name = serializers.CharField(source='agency.agency_name', read_only=True)
    class Meta:
        model = Branch
        fields = [
            'id', 'slug', 'name', 'agency_name',
            'phone_number', 'email', 'city', 'address', 'country',
            'latitude', 'longitude', 
            'opening_time', 'closing_time',
            'is_pickup_point', 'is_dropoff_point', 'is_active'
        ]

# adding a BranchSerializer for the branches API
class BranchSerializer(serializers.ModelSerializer):
    # Show agency name instead of ID
    agency_name = serializers.CharField(source='agency.agency_name', read_only=True)
    
    class Meta:
        model = Branch
        fields = ['id',
                'name',
                'agency_name',
                'city',
                'slug',
                'address',
                'latitude',
                'longitude',
                'opening_time',
                'closing_time',
                'is_active',
                ]
        read_only_fields = ['slug', 'agency_name'] # this one is generated by the model save() method