# Generated by Django 6.0 on 2025-12-16 17:41

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGistExtension  # ← Import this to use the extension GIST



class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('car_rental_app', '0002_vehicle_booking_vehiclespecs'),
    ]

    operations = [
        BtreeGistExtension(), # added this line to enable the extension GIST
        migrations.RenameField(
            model_name='agency',
            old_name='name',
            new_name='agency_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_agency_admin',
            new_name='is_staff',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='agency',
        ),
        migrations.AddField(
            model_name='agency',
            name='city',
            field=models.CharField(choices=[('PATONG', 'Patong'), ('KATA', 'Kata'), ('KARON', 'Karon'), ('PHUKET_TOWN', 'Phuket Town'), ('KAMALA', 'Kamala'), ('BANG_TAO', 'Bang Tao'), ('RAWAI', 'Rawai'), ('CHALONG', 'Chalong')], default='PATONG', max_length=50),
        ),
        migrations.AddField(
            model_name='agency',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agency',
            name='submitted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='agency',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='verification_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('AGENCY_ADMIN', 'Agency Admin'), ('AGENCY_STAFF', 'Agency Staff'), ('PLATFORM_ADMIN', 'Platform Admin')], default='CUSTOMER', help_text='Role of the user in the system', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='car_rental_app.agency'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiclespecs',
            name='transmission',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic'), ('SEMI_AUTOMATIC', 'Semi-Automatic'), ('NA', 'N/A')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['vehicle', 'start_date', 'end_date'], name='car_rental__vehicle_c93863_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='end_date_after_start_date'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('vehicle', '='), (models.Func(models.F('start_date'), models.F('end_date'), function='tstzrange', output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField()), '&&')], name='exclude_overlapping_bookings'),
        ),
    ]
