# Generated by Django 6.0 on 2025-12-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0003_rename_name_agency_agency_name_and_more'),
    ]

    operations = [
    ]
