# Generated by Django 6.0 on 2026-01-01 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('SCOOTER', 'Scooter'), ('BIG_BIKE', 'Big_Bike'), ('BICYCLE', 'Bicycle')], max_length=20)),
                ('daily_rental_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('licence_plate', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RENTED', 'Rented'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20)),
                ('owner_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.agency')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic'), ('SEMI_AUTOMATIC', 'Semi-Automatic'), ('NA', 'N/A')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], max_length=20)),
                ('seats', models.PositiveIntegerField()),
                ('engine_capacity_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('is_air_conditioned', models.BooleanField(default=False)),
                ('is_helmet_included', models.BooleanField(default=False)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='vehicles.vehicle')),
            ],
        ),
    ]
