# Generated by Django 6.0 on 2026-01-03 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_remove_location_agency_branch'),
        ('vehicles', '0002_vehicle_created_at_vehicle_model_vehicle_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_location',
            field=models.ForeignKey(blank=True, help_text='Current physical location of this vehicle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parked_vehicles', to='branches.branch'),
        ),
    ]
